"""empty message

Revision ID: 07d1a2807aca
Revises: 1ab971d5de27
Create Date: 2017-12-12 13:27:01.834759

"""

# revision identifiers, used by Alembic.
revision = '07d1a2807aca'
down_revision = '1ab971d5de27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_types')
    # ### end Alembic commands ###
