"""empty message

Revision ID: dd815d3643b5
Revises: 07d1a2807aca
Create Date: 2017-12-12 13:35:00.452173

"""

# revision identifiers, used by Alembic.
revision = 'dd815d3643b5'
down_revision = '07d1a2807aca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('risk_type', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_fields')
    # ### end Alembic commands ###
